name: gestion_tache
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Correctement défini comme dépendance ici

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  background_color: "#000000"

flutter_native_splash:
  color: "#000000" # Couleur de fond de l'écran de démarrage
  image: "assets/images/logo.png" # Chemin du logo
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
